# Site
name: "VNCrypto"
title: "VNCrypto"
description: "We passionate about blockchain and crypto currency."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: https://vietnamcrypto.github.io
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: vucuong.marketing@gmail.com

# Authors
authors:
  sal:
    name: Cuong Pham 
    display_name: CuongPM
    avatar: 'assets/images/avatar-sal.png'
    email: vucuong.marketing@gmail.com
    web: https://cuongsocial.com
    twitter: https://www.facebook.com/cuong.phamvu.7796/
    description: "We passionate about blockchain and crypto currency."
  john:
    name: Nam Lee 
    display_name: Nam Lee 
    avatar: 'assets/images/avatar.png'
    email: hoainam19031997@gmail.com
    web: https://vietnamcrypto.github.io
    twitter: https://twitter.com/wowthemesnet
    description: "We passionate about blockchain and crypto currency."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
